name: Build docker image

on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Publish to Docker Hub
      uses: home-kops/actions/.github/actions/publish-docker-image@main
      with:
        image_name: telegraf-snmp
        dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
